kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-quarkus
  labels:
    app: hello-quarkus
    app.kubernetes.io/component: hello-quarkus
    app.kubernetes.io/instance: hello-quarkus
    app.kubernetes.io/part-of: java-demo
    app.openshift.io/runtime-version: latest
spec:
  to:
    kind: Service
    name: hello-quarkus
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted