kind: Service
apiVersion: v1
metadata:
  name: hello-quarkus
  labels:
    app: hello-quarkus
    app.kubernetes.io/component: hello-quarkus
    app.kubernetes.io/instance: hello-quarkus
    app.kubernetes.io/part-of: java-demo
    app.openshift.io/runtime-version: latest
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: hello-quarkus
    deploymentconfig: hello-quarkus
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}