kind: Service
apiVersion: v1
metadata:
  name: spring-boot
  labels:
    app: spring-boot
    app.kubernetes.io/component: spring-boot
    app.kubernetes.io/instance: spring-boot
    app.kubernetes.io/part-of: java-demo
    app.openshift.io/runtime-version: latest
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    app: spring-boot
    deploymentconfig: spring-boot
  type: ClusterIP
  sessionAffinity: None