kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: spring-boot
  labels:
    app: spring-boot
    app.kubernetes.io/component: spring-boot
    app.kubernetes.io/instance: spring-boot
    app.kubernetes.io/part-of: java-demo
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: spring-boot
    deploymentconfig: spring-boot
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot
        deploymentconfig: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: sqtran/spring-boot
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler